### ISSUE TITLE
Add `--html` and `--xml` options to `ronin-web diff`

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-web#79]
Add `--html` and `--xml` options to the `ronin-web diff` command to allow switching from `Nokogiri::HTML(...)` to `Nokogiri::XML(...)`.

**Comment by santhosh-chinnasamy** [comment]
@postmodern I am working on this issue

**Comment by postmodern** [comment]
Implemented by b2e8353 by @santhosh-chinnasamy.
